name = "Yeppp"
uuid = "50a6dbef-fe5c-4a38-a4b8-b7ab1a0fcf5f"
authors = ["Jonathan Doucette"]
version = "0.1.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "LinearAlgebra"]
